import { useEffect, useState } from 'react'
import { api } from '../api.js'
import { Card, ErrorNote, StatusPill } from '../components/Badges.jsx'

function TicketTable({ tickets, emptyText }) {
  if (!tickets.length) return <div className="empty">{emptyText}</div>
  return (
    <table>
      <thead>
        <tr>
          <th>Ticket</th>
          <th>Issue</th>
          <th>Category</th>
          <th>Status</th>
          <th>Assigned team</th>
          <th>Source policy</th>
          <th>Origin</th>
        </tr>
      </thead>
      <tbody>
        {tickets.map((ticket) => (
          <tr key={ticket.ticket_id}>
            <td className="cell-id">{ticket.ticket_id}</td>
            <td className="cell-issue">
              {ticket.issue_summary}
              {ticket.next_action && (
                <div className="small" style={{ marginTop: 3 }}>
                  <strong>Next:</strong> {ticket.next_action}
                </div>
              )}
            </td>
            <td className="small">{ticket.category}</td>
            <td className="small">{ticket.status}</td>
            <td className="small">{ticket.assigned_team || '-'}</td>
            <td className="small mono">
              {(ticket.related_policy || ticket.source_policy || []).join(', ') || '-'}
            </td>
            <td>
              <span
                className={`badge ${
                  ticket.origin === 'data_pack' ? 'badge-slate' : 'badge-blue'
                }`}
              >
                {ticket.origin === 'data_pack' ? 'data pack' : 'agent-created'}
              </span>
            </td>
          </tr>
        ))}
      </tbody>
    </table>
  )
}

export function Tickets({ refreshKey }) {
  const [data, setData] = useState({ active: [], closed: [] })
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    setLoading(true)
    api
      .tickets()
      .then(setData)
      .catch((err) => setError(err.message))
      .finally(() => setLoading(false))
  }, [refreshKey])

  if (loading) return <div className="loading">Loading tickets...</div>

  return (
    <>
      <ErrorNote message={error} />
      <Card
        title="Active tickets"
        hint="These require action"
        right={<StatusPill active />}
      >
        <TicketTable tickets={data.active} emptyText="No active tickets." />
      </Card>
      <Card
        title="Closed tickets / history"
        hint="Kept visible as history and precedent - not policy"
        right={<StatusPill active={false} />}
      >
        <TicketTable tickets={data.closed} emptyText="No closed tickets." />
      </Card>
      <p className="muted small">
        Tickets marked <strong>agent-created</strong> were generated by this prototype
        during the current session and use synthetic <code>NEW-1xxx</code> IDs so they
        are never confused with the supplied ticket queue.
      </p>
    </>
  )
}
